# Generated by Django 4.0.6 on 2022-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('Mobile', models.CharField(max_length=10, unique=True, verbose_name='Mobile')),
                ('Role', models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('editor', 'editor')], default='student', max_length=200)),
                ('Country', models.CharField(max_length=50, null=True)),
                ('Nationality', models.CharField(max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
