# Generated by Django 4.0.6 on 2022-07-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_active_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Role',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('editor', 'editor'), ('admin', 'admin')], default='student', max_length=200),
        ),
    ]
